CREATE TABLE [tbl_Propiedades_temp] (
	[PROP_Id] AUTOINCREMENT,
	[PROP_FechaIngreso] DATETIME,
	[PROP_Inmobiliaria] LONG ,
	[TIPROP_Descripcion] TEXT(50) ,
	[PROV_Nombre] TEXT(50) ,
	[LOCAL_Nombre] TEXT(255) ,
	[PART_Nombre] TEXT(255) ,
	[LUGAR_Descripcion] TEXT(30) ,
	[PROP_barrio] TEXT(50) ,
	[PROP_Calle] TEXT(50) ,
	[PROP_Nro] TEXT(10) ,
	[PROP_PisoDpto] TEXT(30) ,
	[PROP_DireccionOtros] MEMO ,
	[PROP_ServAgua] BIT ,
	[PROP_ServLuz] BIT ,
	[PROP_ServGasNatural] BIT ,
	[PROP_ServGasGarrafa] BIT ,
	[PROP_ServCloacas] BIT ,
	[PROP_ServCable] BIT ,
	[PROP_ServTelefono] BIT ,
	[PROP_SupLibre] TEXT(25) ,
	[PROP_SupCubierta] TEXT(25) ,
	[PROP_SupTotal] TEXT(25) ,
	[PROP_Dormitorios] SMALLINT ,
	[PROP_Plantas] SMALLINT ,
	[PROP_Ambientes] SMALLINT ,
	[PROP_Antiguedad] SMALLINT ,
	[PROP_Banos] SMALLINT ,
	[PROP_Edificacion] TEXT(1) ,
	[PROP_Amoblado] BIT ,
	[PROP_Cochera] BIT ,
	[PROP_Dependencia] BIT ,
	[PROP_Parque] BIT ,
	[PROP_VMF] BIT ,
	[PROP_Patio] BIT ,
	[PROP_Pileta] BIT ,
	[PROP_Asfalto] BIT ,
	[PROP_Terraza] BIT ,
	[PROP_DescripcionGeneral] MEMO ,
	[PROP_360] TEXT(50) ,
	[PPROP_Mapa] TEXT(50) ,
	[PROP_Vendido] BIT ,
  [VE_MONEDA] TEXT(2),
  [VE_MONTO] LONG,
  [AL_MONEDA] TEXT(2),
  [AL_MONTO] LONG,
  
	CONSTRAINT [PrimaryKey] PRIMARY KEY ([PROP_Id])
);


INSERT INTO tbl_Propiedades_temp(
PROP_ID,
PROP_FechaIngreso,
PROP_Inmobiliaria,
TIPROP_Descripcion,
PROV_Nombre,
LOCAL_Nombre,
PART_Nombre,
LUGAR_Descripcion,
PROP_barrio,
PROP_Calle,
PROP_Nro,
PROP_PisoDpto,
PROP_DireccionOtros,
PROP_ServAgua,
PROP_ServLuz,
PROP_ServGasNatural,
PROP_ServGasGarrafa,
PROP_ServCloacas,
PROP_ServCable,
PROP_ServTelefono,
PROP_SupLibre,
PROP_SupCubierta,
PROP_SupTotal,
PROP_Dormitorios,
PROP_Plantas,
PROP_Ambientes,
PROP_Antiguedad,
PROP_Banos,
PROP_Edificacion,
PROP_Amoblado,
PROP_Cochera,
PROP_Dependencia,
PROP_Parque,
PROP_VMF,
PROP_Patio,
PROP_Pileta,
PROP_Asfalto,
PROP_Terraza,
PROP_DescripcionGeneral,
PROP_360,
PPROP_Mapa,
PROP_Vendido,
VE_MONEDA,
VE_MONTO,
AL_MONEDA,
AL_MONTO

)

SELECT PROP_Id,
PROP_FechaIngreso,
PROP_Inmobiliaria,
tp.TIPROP_Descripcion,
prov.PROV_Nombre,
l.LOCAL_Nombre,
part.PART_Nombre,
lu.LUGAR_Descripcion,
PROP_barrio,
t1.OP_Id&" "&t2.OP_Id&" "&PROP_Calle,
PROP_Nro,
PROP_PisoDpto,
PROP_DireccionOtros,
PROP_ServAgua,
PROP_ServLuz,
PROP_ServGasNatural,
PROP_ServGasGarrafa,
PROP_ServCloacas,
PROP_ServCable,
PROP_ServTelefono,
PROP_SupLibre,
PROP_SupCubierta,
PROP_SupTotal,
PROP_Dormitorios,
PROP_Plantas,
PROP_Ambientes,
PROP_Antiguedad,
PROP_Banos,
PROP_Edificacion,
PROP_Amoblado,
PROP_Cochera,
PROP_Dependencia,
PROP_Parque,
PROP_VMF,
PROP_Patio,
PROP_Pileta,
PROP_Asfalto,
PROP_Terraza,
PROP_DescripcionGeneral,
PROP_360,
PPROP_Mapa,
PROP_Vendido,
t1.op_monedas_id,
t1.op_monto,
t2.op_monedas_id,
t2.op_monto
FROM ((((((((tbl_Propiedades as p
inner join tbl_PARAM_TiposPropiedad as tp on p.PROP_TIPROP_Id = tp.TIPROP_Id)
inner join tbl_PARAM_Provincias as prov on p.PROP_PROV_Id = prov.PROV_Id)
inner join tbl_PARAM_Localidades as l on p.PROP_LOCAL_Id = l.LOCAL_Id and l.LOCAL_PROV_ID =  p.PROP_PROV_Id)
inner join tbl_PARAM_Lugar as lu on p.PROP_Lugar= lu.Lugar_Id )
inner join tbl_PARAM_Partidos as part on p.PROP_PART_Id = part.PART_Id and part.PART_PROV_Id=p.PROP_PROV_Id and part.PART_LOCAL_ID=p.PROP_LOCAL_Id)
left join tbl_operacionesPosibles as t1 on (t1.op_prop_id=p.prop_id and t1.op_oper_id='VE'))
left join tbl_operacionesPosibles as t2 on (t2.op_prop_id=p.prop_id and t2.op_oper_id='AL'))
left join tbl_PARAM_Inmobiliarias as param on p.prop_inmobiliaria=param.inm_id )
where param.inm_desabilitada = 0

UPDATE tbl_Propiedades_temp
SET PROP_DireccionOtros = Replace (PROP_DireccionOtros , CHR(10), '');
UPDATE tbl_Propiedades_temp
SET PROP_DireccionOtros = Replace (PROP_DireccionOtros , CHR(13), '');
UPDATE tbl_Propiedades_temp
SET PROP_DescripcionGeneral = Replace (PROP_DescripcionGeneral , CHR(10), '');
UPDATE tbl_Propiedades_temp
SET PROP_DescripcionGeneral = Replace (PROP_DescripcionGeneral , CHR(13), '');
